#ifndef TREATSESSION_GLOBAL_H
#define TREATSESSION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TREATSESSION_LIBRARY)
#  define TREATSESSIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TREATSESSIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TREATSESSION_GLOBAL_H
