#ifndef DOCONTROLLER_GLOBAL_H
#define DOCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DOCONTROLLER_LIBRARY)
#  define DOCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DOCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DOCONTROLLER_GLOBAL_H
